module.exports = {
  // TABLE 1 --------- BATCH DETAILS -------------
  COURSE: '#lblCourse',
  BRANCH: '#lblBranch',
  INSTITUTE: '#lblInstitute',

  //TABLE 2 ---------- STUDENT DETAILS ------------
  ROLLNO: '#lblRollNo',
  NAME: '#lblFullName',
  FNAME: '#lblFatherName',
  GENDER: '#lblGender',

  //TABLE 3 ---------- STUDENT MARKS --------------
  // ALL SEMESTER IDs
  FIRST_SEM_BASE_ID: '#ctl04_ctl00_',
  SECOND_SEM_BASE_ID: '#ctl04_ctl01_',
  THIRD_SEM_BASE_ID: '#ctl05_ctl00_',
  FOURTH_SEM_BASE_ID: '#ctl05_ctl01_',
  FIFTH_SEM_BASE_ID: '#ctl06_ctl00_',
  SIXTH_SEM_BASE_ID: '#ctl06_ctl01_',
  SEVENTH_SEM_BASE_ID: '#ctl07_ctl00_',
  EIGHTH_SEM_BASE_ID: '#ctl07_ctl01_',

  // APPEND THIS TO SEMESTER BASE ID TO GET ID OF ANY SEMESTER
  SEM_ID: 'lblSemesterId',
  //APPEND THIS TO SEMESTER BASE ID TO GET TOTAL SUBJECT COUNT OF THAT SEMESTER
  SUBJECT_COUNT: 'lblTotalSubjectsCount',
  //APPEND THIS TO SEMESTER BASE ID TO GET TOTAL THEORY SUBJECT COUNT OF THAT SEMESTER
  THEORY_SUBJECT_COUNT: 'lblTheorySubjectsCount',
  //APPEND THIS TO SEMESTER BASE ID TO GET TOTAL PRACTICAL SUBJECT COUNT OF THAT SEMESTER
  PRACTICAL_SUBJECT_COUNT: 'lblPracticalSubjects',
  //APPEND THIS TO SEMESTER BASE ID TO GET TOTAL OBTAINED OF THAT SEMESTER
  TOTAL_MARKS_OBTAINED: 'lblSemesterTotalMarksObtained',
  //APPEND THIS TO SEMESTER BASE ID TO GET RESULT STATUS OF THAT SEMESTER
  RESULT_STATUS: 'lblResultStatus',
  //APPEND THIS TO SEMESTER BASE ID TO GET SGPA OF THAT SEMESTER
  SGPA: 'lblSGPA',
  //APPEND THIS TO SEMESTER BASE ID TO GET SUBJECT NAME, CODE AND MARKS OF THAT SEMESTER
  ALL_SUBJECT_MARKS: 'ctl00_grdViewSubjectMarksheet'
};
